<?php
// database/seeders/RentTransactionSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class RentTransactionSeeder extends Seeder
{
        public function run(): void
        {
            DB::table('rent_transactions')->insert([
                [
                    'product_id' => 1,
                    'region_id' => 1,
                    'renter_name' => 'Budi Santoso',
                    'renter_phone' => '08123456789',
                    'rent_date' => now()->subDays(2),
                    'rent_price' => 100000,
                    'expected_return_date' => now()->addDays(1),
                    'qty' => 1,
                    'return_date' => null,
                    'status' => 'rented',
                    'notes' => 'Dipinjam untuk presentasi.',
                    'pickup_proof_url' => 'https://picsum.photos/200',
                    'return_proof_url' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'product_id' => 2,
                    'region_id' => 1,
                    'renter_name' => 'Siti Aminah',
                    'renter_phone' => '082112345678',
                    'rent_date' => now()->subDays(10),
                    'rent_price' => 150000,
                    'expected_return_date' => now()->subDays(3),
                    'qty' => 1,
                    'return_date' => now()->subDays(2),
                    'status' => 'returned',
                    'notes' => 'Sudah dikembalikan tepat waktu.',
                    'pickup_proof_url' => 'https://picsum.photos/201',
                    'return_proof_url' => 'https://picsum.photos/202',
                    'created_at' => now()->subDays(10),
                    'updated_at' => now()->subDays(2),
                ],
                [
                    'product_id' => 1,
                    'region_id' => 2,
                    'renter_name' => 'Andi Wijaya',
                    'renter_phone' => '085678901234',
                    'rent_date' => now()->subDays(1),
                    'rent_price' => 100000,
                    'expected_return_date' => now()->addDays(2),
                    'qty' => 2,
                    'return_date' => null,
                    'status' => 'rented',
                    'notes' => 'Dipinjam untuk kebutuhan kantor.',
                    'pickup_proof_url' => 'https://picsum.photos/210',
                    'return_proof_url' => null,
                    'created_at' => now()->subDays(1),
                    'updated_at' => now()->subDays(1),
                ],
                [
                    'product_id' => 2,
                    'region_id' => 2,
                    'renter_name' => 'Rina Marlina',
                    'renter_phone' => '081345678901',
                    'rent_date' => now()->subDays(7),
                    'rent_price' => 100000,
                    'expected_return_date' => now()->subDays(2),
                    'qty' => 1,
                    'return_date' => null,
                    'status' => 'overdue',
                    'notes' => 'Terlambat 2 hari, sudah dihubungi.',
                    'pickup_proof_url' => 'https://picsum.photos/203',
                    'return_proof_url' => null,
                    'created_at' => now()->subDays(7),
                    'updated_at' => now()->subDays(2),
                ],
                [
                    'product_id' => 1,
                    'region_id' => 1,
                    'renter_name' => 'Joko Prasetyo',
                    'renter_phone' => '082298765432',
                    'rent_date' => now()->subDays(5),
                    'rent_price' => 100000,
                    'expected_return_date' => now()->subDays(1),
                    'qty' => 1,
                    'return_date' => null,
                    'status' => 'rented',
                    'notes' => 'Jatuh tempo kemarin, belum kembali (overdue implicit).',
                    'pickup_proof_url' => 'https://picsum.photos/204',
                    'return_proof_url' => null,
                    'created_at' => now()->subDays(5),
                    'updated_at' => now()->subDays(1),
                ],
                [
                    'product_id' => 2,
                    'region_id' => 2,
                    'renter_name' => 'Dewi Lestari',
                    'renter_phone' => '081212343210',
                    'rent_date' => now()->subDays(12),
                    'rent_price' => 250000,
                    'expected_return_date' => now()->subDays(5),
                    'qty' => 3,
                    'return_date' => now()->subDays(4),
                    'status' => 'returned',
                    'notes' => 'Sewa 3 unit untuk event.',
                    'pickup_proof_url' => 'https://picsum.photos/205',
                    'return_proof_url' => 'https://picsum.photos/206',
                    'created_at' => now()->subDays(12),
                    'updated_at' => now()->subDays(4),
                ],
            ]);
        }
}
