version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/http.d/default.conf
      - storage_data:/var/www/html/storage
    depends_on:
      - db

  db:
    image: postgres:16-alpine # Atau mysql:8.0 jika di lokal kamu pakai MySQL
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-sewa_barang}
      POSTGRES_USER: ${DB_USERNAME:-sewa_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password_rahasia_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  storage_data:
